const entityImpactedOptions = [
  "State Data Centre, Maharashtra",
  "State Data Centre, Sikkim",
  "Adani Electricity Mumbai Limited",
  "Airtel",
  "Andhra Pradesh State Load Despatch Centre",
  "Assam State Load Despatch Centre",
  "Axis Bank ",
  "Bangalore Electricity Supply Company Limited",
  "Bank of Baroda  ",
  "Bank of India",
  "BBMB SLDC ",
  "Bharat Sanchar Nigam Limited (BSNL)",
  "Bihar State Load Despatch Centre",
  "Bombay Stock Exchange Limited",
  "BSES Rajdhani Power Ltd ",
  "BSES Yamuna Power Ltd",
  "Calcutta Electricity Supply Corporation Limited",
  "Canara Bank",
  "CCTNS (Crime and Criminal Tracking Network and System), GOA",
  "CCTNS (Crime and Criminal Tracking Network and System), Madhya Pradesh",
  "Central Bank of India",
  "Central Depository Services Limited",
  "Chhattisgarh State Load Despatch Centre",
  "Chhattisgarh Government",
  "Damodar Valley Corporation SLDC",
  "Delhi State Load Despatch Centre",
  "DG Shipping",
  "DVC State Load Despatch Centre",
  "Electricity Department, Govt. of Puducherry",
  "Gas Authority of India Ltd",
  "Goa State Load Despatch Centre",
  "Goods & Services Tax Network",
  "Grid Controller of India Limited",
  "Gujarat State Load Despatch Centre",
  "Haryana State Load Despatch Centre",
  "HDFC Bank",
  "Himachal Pradesh State Load Despatch Centre",
  "ICICI Bank",
  "IDBI Bank",
  "Indian Bank",
  "Indian Clearing Corporation Limited ",
  "Indian Oil Corporation Limited",
  "Indian Space Research Organisation, ISRO Telemetry Tracking and Command Network (ISTRAC)",
  "Indian Space Research Organisation, Master Control Facility (MCF)",
  "Indian Space Research Organisation, Satish Dhawan Space Centre SHAR (SDSC SHAR)",
  "Jammu & Kashmir State Load Despatch Centre",
  "Jharkhand State Load Despatch Centre",
  "Jio",
  "Karnataka State Load Despatch Centre",
  "Kerala State Load Despatch Centre",
  "Kotak Mahindra Bank",
  "Life Insurance Corporation of India",
  "Madhya Pradesh Madhya Kshetra Vidyut Vitaran Company Limited",
  "Madhya Pradesh Pashchim Kshetra Vidyut Vitaran Company Limited",
  "Madhya Pradesh Poorv Kshetra Vidyut Vitaran Company Limited",
  "Madhya Pradesh State Load Despatch Centre",
  "Madhya Pradesh Tribal Affairs Automation System (MPTAAS)",
  "Mahanagar Telephone Nigam Limited (MTNL)",
  "Maharashtra State Load Despatch Centre",
  "Meghalaya State Load Despatch Centre",
  "Metropolitan Clearing Corporation of India Ltd",
  "Metropolitan Stock Exchange of India Ltd",
  "Mizoram  Government",
  "MPSDC (State Date Centre)",
  "MPSEDC  (State Wide Area Network)",
  "Multi Commodity Exchange Clearing Corporation Ltd (MCXCCL)",
  "Multi Commodity Exchange of India Ltd (MCX)",
  "National Health Authority",
  "National Informatics Centre",
  "National Payments Corporation of India",
  "National Physical Laboratory ",
  "National securities Depository Limited",
  "National Stock Exchange Clearing Limited",
  "National Stock Exhange of India Limited",
  "Noida Power Company Limited",
  "Odisha State Load Despatch Centre",
  "Odisha State Wide Area Network",
  "Paytm Payments Bank Ltd.",
  "Power Grid Corporation of India Limited",
  "Puducherry State Load Despatch Centre",
  "Punjab National Bank",
  "Punjab State Load Despatch Centre",
  "Punjab State Power Corporation Limited",
  "Railtel",
  "Rajasthan State Load Despatch Centre",
  "Registrar General and Census Commissioner of India (O/o RG & CCI)",
  "Reserve Bank of India",
  "Southern Power Distribution Company of Telangana Ltd",
  "State Bank of India",
  "State Data Centre,Odisha",
  "Tamil Nadu State Load Despatch Centre",
  "TANGEDCO",
  "Tata Power Company Limited",
  "Tata Power Delhi Distribution Ltd",
  "Telangana State Load Despatch Centre",
  "Torrent Power Limited",
  "Union Bank of India",
  "Unique Identification Authority of India ",
  "Uttar Pradesh State Load Despatch Centre",
  "Uttarakhand State Load Despatch Centre",
  "Vodafone",
  "West Bengal State Electricity Distribution Company Ltd",
  "West Bengal State Load Despatch Centre",
  "Yes Bank",
];

export default entityImpactedOptions;
